-- Add new fields for artist profiles
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "region" TEXT NOT NULL DEFAULT 'Tampa Bay';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "genres" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "popularity" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "followers" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "youtubeUrl" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "tiktokUrl" TEXT;
